# Base configuration for MAMBA-TrackingBERT

data:
  data_dir: "data/processed"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  batch_size: 128  # Optimized for 12GB GPU
  num_workers: 4
  pin_memory: true
  track_length_range: [4, 8]  # As per paper
  volumes: [7, 8, 9]  # Pixel detector volumes
  max_tracks_per_event: 10000

model:
  # Tokenizer settings
  vocab_size: 20000  # Number of unique detector modules
  pad_token_id: 0
  mask_token_id: 1
  
  # MAMBA architecture
  d_model: 64  # Embedding dimension
  d_state: 16  # State dimension for SSM
  d_conv: 4    # Convolution width
  expand: 2    # Expansion factor for inner dimension
  n_layers: 6  # Number of MAMBA blocks
  dropout: 0.1
  
  # Task heads
  mdm_hidden_dim: 256
  ntp_hidden_dim: 128
  
  # Memory optimization
  gradient_checkpointing: true
  mixed_precision: true
  
training:
  num_epochs: 200
  learning_rate: 0.001
  weight_decay: 0.01
  warmup_steps: 1000
  
  # Optimizer
  optimizer: "adamw"
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 0.00000001
  
  # Learning rate scheduler
  scheduler: "cosine"
  min_lr: 1e-6
  
  # Loss weights
  mdm_weight: 1.0
  ntp_weight: 0.5
  
  # Masking strategy
  initial_mask_rate: 0.15
  intermediate_mask_rate: 0.30
  final_mask_rate: 0.50
  mask_schedule_epochs: [50, 100]
  
  # GPU memory optimization
  accumulation_steps: 4  # Gradient accumulation for larger effective batch size
  amp_enabled: true  # Automatic mixed precision
  memory_efficient_attention: true
  
  # Regularization
  label_smoothing: 0.1
  gradient_clip_val: 1.0
  
  # Checkpointing
  save_every_n_epochs: 10
  checkpoint_dir: "checkpoints"
  keep_last_n_checkpoints: 3
  
evaluation:
  metrics: ["accuracy", "f1", "precision", "recall"]
  distance_threshold: 20.0  # mm, for MDM evaluation
  
logging:
  log_every_n_steps: 100
  tensorboard_dir: "logs/tensorboard"
  wandb_project: "mamba-trackingbert"
  wandb_entity: null
  
hardware:
  gpu_memory_limit: 12000  # MB
  num_gpus: 1
  distributed_backend: "ddp"
  
seed: 42
deterministic: true
